version: '3.9'

services:

  backend:
    image: backend:latest
    build: 
      context: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI="mongodb://citizix:S3cret@db:27017"
    env_file:
      - .env

  db:
    image: mongo:6.0.1-focal
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_REPLICA_HOST=0.0.0.0
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://citizix:S3cret@db:27017